### PR TITLE
Refactor msp430/x2xxx/usci to enable SPI on USCI A

### PR DESCRIPTION
**Pull request by tgtakaoka**
The idea behind this refactoring is splitting HplMsp430UsciA and
HplMsp430UsciB interfaces into four function specific interfaces.

  - HplMsp430Usci: common USCI HPL of A and B.
  - HplMsp430UsciSpi: SPI specific USCI HPL shared between A and B.
  - HplMsp430UsciUart: UART specific USCI HPL for A.
  - HplMsp430UsciI2C: I2C specific USCI HPL for B.

This is just interfaces and configurations change and contains no
logical difference.

### CODE REVIEW

**Comment by tgtakaoka** [comment]
This pull request addresses [issue#28](https://github.com/tp-freeforall/prod/issues/28).

**Comment by cire831** [comment]
does this close issue #28?

**Comment by tgtakaoka** [comment]
Yes, I think so.

I confirmed that configuring SPI on USCI A0, A1, B0, B1 of msp430f2617 are compiled without error, though I didn't confirm an actual SPI functionarilty.

**Comment by cire831** [comment]
do you have access to any msp4302618 or similar development boards from TI?

that is one of the x2 family processors.

**Comment by tgtakaoka** [comment]
I have raw msp430f2618 chip ready on breadboard in hand. I'll check SPI functionality when I find spare time.
img_20180527_170514

**Comment by cire831** [comment]
sound good.  thanks.

the approarch to the seperation looks similar to what I did on the x5 and on the msp432 code.  looks good.

**Comment by tgtakaoka** [comment]
Sorry for the delay, but I finally found a time to confirm.
SPI functionality on USCI A0, A1, B0, B1 work fine on MSP430F2618.

Please have an another look.
Thanks.

**Pull request merged**
